name: PlayTitle
version: 3.0
main: me.miguel.title.Main
api-version: 1.20

commands:

  title:
    description: Define um titulo

  cores:
    description: Mostra cores

  criargrupo:
    description: Cria grupos

  settitleinicial:
    description: Define titulo inicial

  unsettitleinicial:
    description: Remove titulo inicial

permissions:

  title.admin:
    default: op
