name: PlayTitle
version: 2.0
main: me.miguel.title.Main
api-version: 1.16

commands:
  title:
    description: Define títulos

  cores:
    description: Mostra todas as cores

  settitleinicial:
    description: Define título inicial

  unsettitleinicial:
    description: Remove título inicial

permissions:
  title.admin:
    default: op
